package AsociacionVecinos;

/**
 *
 * @author Jenderson Quintero y Norangel Marín.
 */
public class Interfaz extends javax.swing.JFrame {

    Funcionalidades f;
            
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        f = new Funcionalidades();
        f.t.cargarDatos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        marco = new javax.swing.JPanel();
        buscarVecino = new javax.swing.JButton();
        buscarHabitantes = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        año = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(102, 204, 255));
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Asociación de Vecinos");
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 290, 50));

        marco.setBackground(new java.awt.Color(0, 153, 153));
        marco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        buscarVecino.setBackground(new java.awt.Color(255, 255, 255));
        buscarVecino.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buscarVecino.setForeground(new java.awt.Color(0, 0, 0));
        buscarVecino.setText("Buscar Vecino");
        buscarVecino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarVecinoActionPerformed(evt);
            }
        });

        buscarHabitantes.setBackground(new java.awt.Color(255, 255, 255));
        buscarHabitantes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buscarHabitantes.setForeground(new java.awt.Color(0, 0, 0));
        buscarHabitantes.setText("Buscar Habitantes del Apartamento");
        buscarHabitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarHabitantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout marcoLayout = new javax.swing.GroupLayout(marco);
        marco.setLayout(marcoLayout);
        marcoLayout.setHorizontalGroup(
            marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarVecino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarHabitantes, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        marcoLayout.setVerticalGroup(
            marcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buscarVecino, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buscarHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        fondo.add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 370, 190));

        salir.setBackground(new java.awt.Color(204, 0, 0));
        salir.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        salir.setText("x");
        salir.setAlignmentY(0.0F);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        fondo.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 40, 30));

        año.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        año.setForeground(new java.awt.Color(0, 0, 0));
        año.setText("2020");
        fondo.add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("© Norangel Marin y Jenderson Quintero");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 284, -1, 20));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void buscarVecinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarVecinoActionPerformed
        f.buscarVecinos();
    }//GEN-LAST:event_buscarVecinoActionPerformed

    private void buscarHabitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarHabitantesActionPerformed
        f.buscarHabitantes();
    }//GEN-LAST:event_buscarHabitantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel año;
    private javax.swing.JButton buscarHabitantes;
    private javax.swing.JButton buscarVecino;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel marco;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

}
